version: "3"
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /var/monlog/prometheus/etc:/etc/prometheus
      - /var/monlog/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

    restart: always
           
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - /var/monlog/alertmanager/etc/:/etc/alertmanager/
      - /var/monlog/alertmanager/data:/alertmanager
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager' 

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - /var/monlog/loki/loki:/loki
      - /var/monlog/loki/etc:/etc/loki
      - /var/monlog/loki/wal:/wal
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail
    volumes:
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id  
      - /var/monlog/promtail:/etc/promtail:rw
    command: '-config.file=/etc/promtail/config.yml'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - 3000:3000
    volumes:
      - /var/monlog/grafana/data:/var/lib/grafana
      - /var/monlog/grafana/etc:/etc/grafana
      - /var/monlog/grafana/logs:/var/log/grafana
      - /var/monlog/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - /var/monlog/grafana/config.monitoring
#    command: -config.file=/var/monlog/grafana/etc/grafana.ini
    restart: always

