version: "3"
volumes:
    prometheus_data: {}
    grafana_data: {}
    loki_data: {}
networks:
  loki:
  front-tier:
  back-tier:
services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
#      - pushgateway:pushgateway
    networks:
      - back-tier
    restart: always
           
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'    
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id  
      - ./promtail:/etc/promtail
    command: '-config.file=/etc/promtail/config.yml'
    networks:
      - loki

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana
#      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
#    command: -config.file=./grafana/grafana.ini
    networks:
      - back-tier
      - front-tier
      - loki
    restart: always

